name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Check Tests
        id: check-tests
        uses: ./.github/actions/check-tests.yml

      - name: Build and Deploy (Add your build/deploy steps here)
        if: steps.check-tests.outputs.tests_passed == 'true'
        run: |
          # Add your build and deploy commands here
          # This step will only run if the tests pass
