name: Continuous Integration

on:
  pull_request:
    branches:
      - adn_working

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Merge Changes (if tests pass)
        if: ${{ success() }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main
          git merge --no-ff --no-commit adn_working
          git commit -m "Merge adn_working into main"
          git push origin main
